---
- name: Import common playbook
  ansible.builtin.import_playbook: common.yml

- name: Import ufw playbook
  ansible.builtin.import_playbook: ufw.yml

- name: Import node_exporter playbook
  ansible.builtin.import_playbook: node_exporter.yml

- name: Import docker playbook
  ansible.builtin.import_playbook: docker.yml

- name: Import monitoring playbook
  ansible.builtin.import_playbook: monitoring.yml

- name: Import semaphore playbook
  ansible.builtin.import_playbook: semaphore.yml
